name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUBY_VERSION: '3.2.3'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client libpq-dev

    - name: Create database
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/my_site_test
        RAILS_ENV: test
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      run: |
        bin/rails db:create
        bin/rails db:schema:load

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/my_site_test
        RAILS_ENV: test
      run: bundle exec rspec
        
    - name: Run security audit
      run: bundle exec brakeman --no-pager
        
    - name: Check code style
      run: bundle exec rubocop

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Navigate to app directory
          cd /var/www/my-site

          # Pull latest code (or clone if first time)
          if [ -d ".git" ]; then
            # Fix git pull conflict by forcing update
            git fetch origin main
            git reset --hard origin/main
          else
            git clone https://github.com/atornow/my-site.git .
          fi

          # Stop existing containers
          docker-compose down || true

          # Build new image (this is fast since it's local)
          docker build -t my-site:latest .

          # Clean up orphaned containers
          docker-compose down --remove-orphans || true

          # Run database migrations directly with docker (bypassing docker-compose service name issues)
          docker run --rm --network=host \
            -e RAILS_ENV=production \
            -e DATABASE_URL="postgresql://my_site_user:${DATABASE_PASSWORD}@localhost:5432/my_site_production" \
            -e RAILS_MASTER_KEY="${RAILS_MASTER_KEY}" \
            -e ADMIN_PASSWORD="${ADMIN_PASSWORD}" \
            my-site:latest bin/rails db:migrate

          # Start services with environment variables  
          RAILS_MASTER_KEY="${RAILS_MASTER_KEY}" DATABASE_PASSWORD="${DATABASE_PASSWORD}" ADMIN_PASSWORD="${ADMIN_PASSWORD}" docker-compose up -d

          # Clean up old images (keep disk space manageable)
          docker image prune -f

          # Health check with more detailed output
          sleep 15
          echo "Checking health..."
          RESPONSE=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:3000/ || echo "000")
          echo "Health check response: $RESPONSE"

          if [ "$RESPONSE" != "200" ]; then
            echo "Health check failed! Response code: $RESPONSE"
            echo "Checking logs..."
            docker-compose logs --tail=50
            exit 1
          fi

          echo "Deployment successful!"